### ISSUE TITLE
Error while processing RsRecipeShaped

### ISSUE THREAD

**Issue by 0Navis0** [bdew-minecraft/generators#102]
I get this error in the log while Minecraft loading, it doesn't provocate any crash, but I don't think that it's normal. http://pastebin.com/faxdT5Dx

**Comment by bdew** [comment]
It means that IC2 was detected by the config system, but the output blocks aren't actually registered. It does mean that you won't be able to produce EU, but otherwise shouldn't cause any issues.

If this is on 1.9.4 - this is known and will be fixed "soon" (tm).

If it's on other versions - what version of MC, this mod and IC2?

**Comment by 0Navis0** [comment]
It's 1.10.2 with industrialcraft-2-2.6.1-ex110

**Comment by bdew** [comment]
Fixed in latest build.
