### ISSUE TITLE
[1.10.2][bug] IC2 energy inconsistent when it should be.

### ISSUE THREAD

**Issue by DaemosDaen** [bdew-minecraft/generators#110]
I have a generator set up as follows:
Gas Turbine Controler
3 Fuel tanks filled with Ethanol from forestry, there is no ethanol shortage possible at this time.
1 fluid intake
I HD capacitor
50 Advanced Alloy Turbines, note these were iron turbines that have been upgraded with kits.
1 EV emitter

I use glass fiber to transmit from the emitter to a EV transformer, then glass cable from there to 3 MFSUs that are mostly empty

thje generator seems to only be transmitting between 500 - 4000 EU/T when it should be a solid 6kEU/t I think or at the very least it should be maxing out at what ever the max is for production due to the empty MFSUs.

Shouldn't be any variance to my knowledge.

**Comment by bdew** [comment]
I think you need a separate transformer per MFSU (or even multiple) to max out the transfer now. 

EV transformers can only output 2048 eu/t when in step down mode, so if you hook up 3 MFSUs to one transformer - it distributes 2048 eu/t between them.

Since the emitter outputs 8192 eu/t the number is jumping as it only sends a packet in ~1/4 ticks.

Added: Or have 4 transformers filling one MFSU. Or just use HV emitters.

**Comment by DaemosDaen** [comment]
Just checking back in that you are correct, I set it up as described and it's bouncing between 3k and 7k

I haven't needed this kind of power in IC2 in a while.
