### ISSUE TITLE
EU Output modules are labeled incorrectly

### ISSUE THREAD

**Issue by drrk** [bdew-minecraft/generators#116]
The various EU emitters are incorrectly labeled, they all emit one tier higher than they say.

For example the LV emitter gives 128EU/t  but this is actually MV (http://wiki.industrial-craft.net/index.php?title=Copper_Cable)

I'm not sure if the power types have changed, but it defiantly caused exploding machines for me.

Running generators 0.9.20.10-mc1.10.2 and IC2 2-2.6.37-ex110

**Comment by bdew** [comment]
Hm, you're right. Will fix.

**Comment by bdew** [comment]
Should be fixed in next build. 
- The current emitters were renamed to match the voltage (so 128 = medium, 512 = high and so on). 
- New LV emitter that outputs 32eu/t and is cheaper to make than the old LV one.
- I've left 8192eu/t one in, it doesn't seem to have a proper name in the new system buy i named it "Insane Voltage" - it will work with IC2 machines with enough transformer upgrades to count as tier 5 (e.g. mass fab with 2 upgrades).
- I've added a tooltip with the tier and output power to all modules which should make it all clearer.
- Existing blocks will change to new power levels, so if you have any placed - this might break builds. Sorry.
