### ISSUE TITLE
possible bug FTB Skyfactory 3 modpack

### ISSUE THREAD

**Issue by wooby6** [bdew-minecraft/generators#123]
Advanced Generators 0.9.20.19
BDLib 1.12.2.19

setup heat exchanger correctly
pumped in lava & water
They don't show in inventory, & are instead voided

**Comment by pksiazek** [comment]
I have same issue.
It seems Advanced Generators are not working properly with Extra Utilities 2 pipes/transfer nodes.
Fluid are taken from tanks and voided.
When I attach Ender IO fluid conduits everything is working fine.

Also both Ender IO item conduits and EU2 pipes are not working properly with item output port.
Visually they attach but there is no colored output.
(direct chest connection is working fine)

Advanced Generators - 0.9.20.19
Ender IO - 1.10.2-3.1.164
Extra Utilities 2 - 1.10.2-2.3.1

Same problem exists farge with only those 3 mods - so it's not Sky Factory related

**Comment by bdew** [comment]
Sorry for the long delay on the fix.

Fluids getting voided should be fixed with [bdlib 1.12.2.21](https://minecraft.curseforge.com/projects/bdlib/files/2373809)

> Also both Ender IO item conduits and EU2 pipes are not working properly with item output port.

This is a known issue, item output ports can only output to something that either implements I(Sided)Inventory or IItemHandler. Chests, barrels, crates, buffers, etc. should work.
