### ISSUE TITLE
Feature request - Add steam producer/Bump IE BioDiesel

### ISSUE THREAD

**Issue by Silvrus** [bdew-minecraft/generators#124]
Hello, great mod, love the whole thing, ~~but I was wondering if it would be possible to add a steam producer to your mod. Currently the only mod I know of in 1.10.2 that produces compatible steam for the Steam Turbine is Extreme Reactors. I was thinking that maybe there could be a configuration, possibly a steam output block, for the Syngas Producer, since it already produces steam during its operation. With a steam output, that could be pumped into the Steam Turbine to run it if there isn't a compatible mod present.~~

Also, while testing out the Gas Turbine, I noticed that the Immersive Engineering BioDiesel only produces 500rf/mb, whereas the Forestry Ethanol produces 800. Can the BioDiesel be bumped up to be equal or nearly equal? Or is there something behind the scenes I'm not aware of?

All in all, love your stuff, keep up the great work!

Edit: It appears I'm a bloody idiot in that I didn't realize what the Heat Exchanger was for. Please disregard the first part of my comment.

**Comment by bdew** [comment]
Fuel energy density is generally balanced around the native value in whatever mod it comes from.

I haven't played with IE for a while, but according to FTB wiki, IE BioDiesel produces 512k RF per bucket in IE diesel (4096RF/t * 20 t/sec * 6.25 sec).

For forestry Ethanol it's a bit more complicated as it can't be directly used to produce RF in forestry itself, and the values in other mods are kinda all over the place, so 800 was chosen as a happy medium. It also involves more steps and more energy investment to produce than IE BioDiesel, so that also makes sense.

Also note that 500 is the base value. Even in an un-upgraded turbine you get 1.1 efficiency bonus (making it 550 rf/mb) and with [upgrades](https://bdew.net/generators/efficiency-upgrades/) you can get to 1.8 bonus.
