### ISSUE TITLE
BUG - Mekanism Universal Cables w/ RF Producer

### ISSUE THREAD

**Issue by Utildayael** [bdew-minecraft/generators#132]
Minor bug which does have a workaround. Universal Cables from Mekanism don't want to attach to the RF producer in Adv Gens. EnderIO conduits work fine. The workaround is to place a Mekanism Energy Cube next to the RF producer and THAT works but they are of course output limited with even the largest cube in Mek being limited to 20k RF/t which is less than a fully built turbine setup [25k]. 

bdlib-1.12.2.21-mc1.10.2
generators-0.9.20.19-mc1.10.2

MC 1.10.2
Forge 12.18.3.2221
Mekanism 1.10.2-9.2.1.295

Thanks

**Comment by bdew** [comment]
I think it's something borked with RF in mekanism cables, i can't get them to work corectly with anything RF-based outside mekanism.

If you use a cube as a buffer i think it converts the power to mekanisms internal power system that then works correctly with the cable.

Also if you have Tesla installed you can use Tesla Generator module instead of Flux Generator and the cables work with it.

Edit: But even using tesla the power goes to the cable but doesn't get transmitted to RF based machines... I think their RF support is just borked.

**Comment by Utildayael** [comment]
Roger. I logged this with Mek and thinking it's their issues with their power. Looks like quite a few others having issues so it's not just adv gen. Thank you sir!
