### ISSUE TITLE
MK1.12 Advanced Generators v0.9.20.5 and Thermal Dynamics

### ISSUE THREAD

**Issue by Kilmatar** [bdew-minecraft/generators#149]
I'm unable to connect fluiducts from Thermal Dynamics to Fluid Intake/output valves.
Is it possible to make an integration with Thermal Dynamics mod?

Trying to supply Syngas Generator with water from TD's Aqueous Accumulator. Fluiduct not connected
![image](https://user-images.githubusercontent.com/4357221/29918879-d9eb2698-8e4f-11e7-9d99-849b7954bbc6.png)

BTW Thermal Expansion's Portable tank accepted as water source. So I create a temporary solution with tank as buffer:

![image](https://user-images.githubusercontent.com/4357221/29919067-85549870-8e50-11e7-9b2d-a56a2507fba2.png)

And now 2 questions:
1. How to output syngas?
2. How to insert wood? Because I think itemducts from Thermal Dynamics is also unsupported :)

**Comment by bdew** [comment]
Hm it should work, i can't reproduce this. Are you running the latest versions of everything?

Inputs should just work.

For outputs you need to right click the side you want with a wrench or crescent hammer so it shows the colored outline (because TD ducts aren't autodetected), and after that it will connect.


![ducts](https://user-images.githubusercontent.com/96327/29952692-b3349258-8ed3-11e7-8327-51ac7b665d3f.png)

**Comment by Kilmatar** [comment]
Oops! My fault! Feel mysel idiot. I'm playing MK1.12 first time and still thinking in terms of MK 1.7.10 where all pipes/tubes were connected automatically.

Sorry :)
