### ISSUE TITLE
[bug 0.9.20.8 (MC 1.12.2)] crafting a gold plated turbine leaves iron turbine rotor

### ISSUE THREAD

**Issue by winsrp** [bdew-minecraft/generators#157]
so if I craft all the way from start to finish an iron plated turbine, the last recipe for the actual turbine block, leaves an iron turbine rotor in the crafting grid like if it were a residue.

**Comment by bdew** [comment]
You mean gold plated?

I guess i had a brain fart when i wrote that section... the gold-plated turbine is set to have an iron-plated turbine as it's "container", so that it's left in the crafting grid when doing the un-crafting recipe... But it also affects the other recipes with it and causes that issue.

I'm going to change the un-crafting recipe so that you get the iron rotor back and lose the gold ingot for now to fix the bug... at least until i can find a more elegant solution.

**Comment by winsrp** [comment]
yeah that was the one, thanks

**Comment by winsrp** [comment]
to be honest, you could just make it a requirement for crafting the gold turbine, and I never knew you could un-craft the turbine O_o

**Comment by bdew** [comment]
In general i allow uncrafting because you can upgrade lower tier turbines to better materials... and get back the lower tier rotor, so i don't want people to be stuck with useless rotors. For most of them you can melt them down back to ingots, but the gold one was special.

**Comment by winsrp** [comment]
I find it fine having to use the upgrade item to upgrade turbines, but I really think you should not return anything when doing so, having stuff back is the real problem, having a bunch of useless items in the end. Just make it so that upgrades are linear, for example, iron -> gold -> something else..... if you make it like branched it really gets weird.
