### ISSUE TITLE
[1.16.5] Heat generator interface crash + bucket consume

### ISSUE THREAD

**Issue by TheSnowyChickens** [bdew-minecraft/generators#199]
Hello,

shift + left click items (in my case coal blocks) in the heat exchanger control interface crash the game.
(Advanced Generators setup: Heat Controller + (okay, ignore this block xd) Heat Chamber + Heat Exchanger)

![grafik](https://user-images.githubusercontent.com/29357962/122683269-6a490200-d1fe-11eb-968c-500d92f52d30.png)

MC: 1.16.5
Forge: 1.16.5 - 36.1.32
AG: 0.10.1.10
SCF: 2.13.5-build-2-with-library
BD: bdlib-1.17.1.10
Optifine and OptiForge: No

+ more mods:
![grafik](https://user-images.githubusercontent.com/29357962/122683373-f5c29300-d1fe-11eb-9b9b-1cb34dec59c6.png)

Crash log / log: actually no logs, because minecraft didn't generate one

---------

Oh, quickly a second thing:
In creative mode, the fluid intake valve consume the water bucket, but in creative that should not be the case.

**Comment by bdew** [comment]
shift-click lockup fixed in [BdLib 1.17.1.11](https://www.curseforge.com/minecraft/mc-mods/bdlib/files/3361259)
bucket thing fixed in [Advanced Generators 0.10.1.11](https://www.curseforge.com/minecraft/mc-mods/advanced-generators/files/3361262)

in the future please open separate reports for separate issues

**Comment by TheSnowyChickens** [comment]
Nice, ty. =)

And sry, I found the bucket "bug" after creating this one and I thought what such a small thing would be too small for it's own issue.
