### ISSUE TITLE
Redstone Control Module only works with 'strong' signals

### ISSUE THREAD

**Issue by MyNameIsKodos** [bdew-minecraft/generators#40]
This is preventing things like Project Red Insulated Wire from being used to control generators.  

Also, a minor related issue is that the block doesn't seem to have the proper traits that let a framed insulated wire connect to it, so you have to use a regular one.  Not sure if that's something easily fixed or not.

**Comment by bdew** [comment]
They need signal getting to the block, rather than adjacent blocks to make compact builds easier without worrying about crosstalk.

I was missing a flag to allow redstone connections, this is now fixed which should make PR wires work correctly - http://i.imgur.com/GpDd2Ly.png

Try this build - http://jenkins.bdew.net/job/generators-1.7.10/92/artifact/build/libs/generators-0.9.16.92-mc1.7.10.jar

**Comment by MyNameIsKodos** [comment]
Issue fixed! Will close with this comment.
