### ISSUE TITLE
Initial start doesn't create config files

### ISSUE THREAD

**Issue by BakermanLP** [bdew-minecraft/generators#5]
Hello,
I am missing the config files after the first start to change some values.
Michael

**Comment by bdew** [comment]
The current system doesn't place them in the config folder, because i have no good way of updating them without overwriting user changes.

What you can do is either
- Create new files in  <minecraft>\config\AdvGenerators using the same format, those will be merged with the internal config when loading
- Extract them from the jar into <minecraft>\config\AdvGenerators\overrides and edit them there (less recommended, you will need to manually update them when new versions come out)
- Edit them inside the jar (not recommended)

I am planning to document this system and make it more user friendly where i can, if you need any problems - contact me and i'll be happy to help.
