### ISSUE TITLE
IfHavemod a good solution?

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [bdew-minecraft/generators#57]
So I was going through the config options and saw this

if HaveMod PneumaticCraft {
        turbine-fuel: diesel 70 MJ/mB
        turbine-fuel: kerosene 110 MJ/mB
        turbine-fuel: fuel 150 MJ/mB
        turbine-fuel: lpg 180 MJ/mB
    }

What if I have Immersive Engineering mod which also adds diesel as a fluid? Wouldn't it be better to rather have something like IfFluidRegistred ? That way it would be independent of any mods. If that's possible to implement at all.

**Comment by bdew** [comment]
Putting IfFluidRegistred on every single fluid would be awfully repetitive :P

I could just remove the check entirely, specifying a fluid that isn't registered doesn't produce an error.

I'll need to think about this.

**Comment by labpaw** [comment]
Also, why are still referring to MJ? Playing with dead things is bad :)

**Comment by bdew** [comment]
It's only used internally as a power unit for now, mostly because I ~~am too lazy~~ didn't get around to rewrite everything and add/remove conversion ratios (that will lead to testing, finding bugs because i missed something, fixing them and more testing).

It doesn't really use the MJ API or show it anywhere a normal user can see it.

**Comment by bdew** [comment]
No more HaveMod  checks
