### ISSUE TITLE
Nuclear Control Energy Sensor Kits Identify Multi Blocks as Energy Blocks

### ISSUE THREAD

**Issue by darth62969** [bdew-minecraft/generators#67]
Outside of when you have capacitors and an RF buffer they shouldn't work, but more importantly the Generator sensor kit does not work on the steam turbines. For monitoring reasons i think you should either add a sensor kit for the generators (if possible, their may not be an API to do it) or fix it so that Either the generator sensor kit or the energy sensor kits work properly, or not at all.

<img src="http://i.imgur.com/Kb8f892.png">

that is what happens when i right click the Steam Turbine or the Heat Exchanger with the energy sensor kit and put the cards in the nuclear control advanced information panels. the steam turbine i get the Heat Exchanger i don't.

**Comment by bdew** [comment]
I'll look into adding support for that when i have the time.

For now you can get somewhat reasonable readings for energy levels and tanks by pointing the cards at the respective I/O blocks. Note that due to the fix to #65 you won't get correct readings from EU emitters, but RF ones (if nuclear control supports that, not sure) should be fine.

You can also use redstone sensor blocks for some monitoring as well.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
