### ISSUE TITLE
Capacitor Controller

### ISSUE THREAD

**Issue by darth62969** [bdew-minecraft/generators#72]
Well I need a block/multiblock to store and take in RF, EU or ProjectRed's energy and output all of those, so i was thinking of adding a Capacitor Controller and the appropriate inputs for the system, but i have no idea where to start. so while i am looking over the code and figuring out how it is structured, and where to start. I wanted to ask if this could be implemented?

**Comment by bdew** [comment]
I'm not opposed to the idea though it could open up some balance issues with other mods since it would be able to convert power between different systems.

If you want to do it yourself you will need to implement the machine/block/tileentity/container/gui classes for the controller, see any of the existing controller packages (e.g. [turbine generator](https://github.com/bdew/generators/tree/mc-1.7.10/src/net/bdew/generators/controllers/turbine)) for example.  

You will also need to implement input blocks for each power system you want to support, no real examples here - they would need to extend BaseModule/TileModule and the respective interfaces for the power system, updating the capacitor in the controller.

The code isn't well commented, so if you have any questions - ask :P

I might look at it myself if you can't/don't, but it will be when i have more time as i'm neck deep in 1.8.9 porting at the moment.

**Comment by darth62969** [comment]
if i could figure out how to get eclipse to work... i would love to. but, i
also have homework to do and i am not too sure how forge works so... i know
java, but looking at your code, yeah... not great for comments, great for
organization however, i still can't figure out what is going on. then i
have no clue how to build it, so yeah.

then the only input i think we will need, is RF because that is more of the
standard for most mods, and the entire point of the Capacitor controller is
to store power, not convert between them. prevents exploits, while also
solving an issue. there is no easy way to convert between RF and EU, since
i am a major fan of IC2 and Gravisuit the only non-op creative flight, i
run into this issue alot, while i don't want to store everything in RF i
would like to have a mass storage option that works, instead of 2 separate
banks of EnderIO capacitors and ic2 MFSUs.

(: Jonathan :)

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
