### ISSUE TITLE
OP ethylene generating.

### ISSUE THREAD

**Issue by BlazingGamer** [bdew-minecraft/generators#85]
Hello, why is Ethylene generating 6k rf/mb? It generates just 800 rf/mb in mek, but with 6k and for example F/A mixer you can create almost 8m rf (plus energy used for separating water, crushing wheat and compressing H2+Water+Wheat to Ethylene) from 2 water buckets and 5 wheat. Isn't it too op? Other than that, this is very cool mod! :)

**Comment by bdew** [comment]
Did you actually check that it produces 800rf/mb? Last time when i was tweaking the numbers i've looked at how much it produces in a gas generator from mekanism and used that as a baseline.

And yeah it's kinda OP, but it's the same level of OP in mekanism itself... so *shrug\* (unless something changed since then).

**Comment by Utildayael** [comment]
It's still pretty high end compared to Mek and out of line with all other fuels for Adv Gens. 

Mek upped their gas burners in 1.9 however to push out up to about 7.8K RF/t and the fuel usage is minimal as you can run a ton of them off one PRC setup. 

Anyway, as you said Mek is OP in ways. Mek does use a crapload of power for things so it's not quite as bad but the gas burners are def OP. 

Discarding that, as it's hard to compare mods to each other, the fuel rating for Adv Gen is pretty high. It is 6x what Syngas is and requires nearly the same setup except A full Syngas setup costs 50x more materials and produces less Syngas per tic than a Mek ethylene setup. 

I would suggest upping the value of SynGas or at least halving the value on Ethylene from Mek.

**Comment by bdew** [comment]
So i've just ran a test with latest mek and a single bucket of Ethylene produces ~11.3M RF per bucket in their gas burning generator... so if anything i need to buff it in AG lol.

Honestly it's just OP by design and i can't fix this from my side. Even if i nerf or blacklist then people can just build an array of GBGs and get the OP power from there, with the added "bonus" of many more ticking tile entities.

And buffing syngas will make it just as OP (power creep anyone?).

As such i decide to not touch it in the default distribution. Pack makers and server admins that want to include Mek can fix it whichever way they want by custom configs.

**Comment by Utildayael** [comment]
Any chance you could change the config from BACON to a more... uh less intimidating form? At least for some basic balancing items like conversion factors between power types and how much power a bucket of x days, maybe a ratio? Like Syngas is 1.0 and Ethylene is 6.0 since it does 6k vs 1k?

Just a thought. Server admin always freaks when I suggest it because he doesn't want to learn your config language. :(

**Comment by bdew** [comment]
What would i change it to? The forge config format is way to limited for the level of tweaking that i allow...

You can just copy [this section](https://github.com/bdew/generators/blob/mc1.10.2/resources/assets/advgenerators/config/turbine.cfg#L130-L176), put it in a file in your config/AdvGenerators folder and edit the values.

**Comment by Utildayael** [comment]
Oh I know and your config is great, it's just intimidating for most. :)

I'll harass him again and give him your link!

Thanks
